version: 0.2

phases:
  install:
    commands:
      - sudo apt-get install unzip
      - wget https://releases.hashicorp.com/terraform/0.11.11/terraform_0.11.11_linux_amd64.zip
      - unzip terraform_0.11.11_linux_amd64.zip
      - sudo mv terraform /usr/local/bin/
      - terraform --version
      - npm install
      - lerna exec npm install
      - npm i -g lerna
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - lerna run deploy
